(package "emp"
         "0.1.0"
         "Emacs Music Playlist")

(website-url "https://github.com/jcs-elpa/emp")
(keywords "multimedia")

(package-file "emp.el")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "async")
(depends-on "buffer-wrap")
(depends-on "f")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
